### ISSUE TITLE
Improvements: To-Do list

### ISSUE THREAD

**Issue by DarkoGNU** [DarkoGNU/SimpleLogo#2]
## Performance

- [ ] **(Parser)** Replace std::regex with something faster
- [ ] **(Parser, Executor)** Transform division into multiplication
- [ ] **(Executor)** Implement optional memoization for command arguments
- [ ] **(Parser, Executor)** When parsing, identify procedures and arguments with numbers instead of std::string
- [ ] **(Executor)** Use a better data structure than a map for procedures and their arguments. Preferentially something contiguous to reduce cache misses
- [ ] **(Turtle)** Faster line drawing algorithm (reduce floating point operations)
- [ ] Implement parallel Logo code execution

## Code quality

- [ ] Implement automated tests for individual classes and methods
- [ ] Implement automated tests for the whole program (source -> image)
- [ ] Run these tests with continuous integration

## Debugging

- [ ] Provide more data when throwing exceptions

## Functionality

- [ ] Implement loops
- [ ] Support negative constants

## Documentation

- [ ] Provide documentation regarding the program usage

I won't personally fix most of these. I've spend a lot of time on SimpleLogo and I've learned a lot about C++, cross-platform development and continuous integration. For me, it's time to move on 🥇
